### ISSUE TITLE
Benchmark fails to complete

### ISSUE THREAD

**Issue by CBenni** [mitchellh/mapstructure#173]
### How to reproduce:

    Run go get github.com/mitchellh/mapstructure
    Go to $GOPATH/github.com/mitchellh/mapstructure
    Run go test -bench .

### Output:
```
goos: linux
goarch: amd64
pkg: github.com/mitchellh/mapstructure
Benchmark_Decode-8                   	  200000	      6111 ns/op
Benchmark_DecodeViaJSON-8            	  300000	      5425 ns/op
Benchmark_DecodeBasic-8              	panic: reflect: reflect.Value.SetInt using unaddressable value

goroutine 49 [running]:
reflect.flag.mustBeAssignable(0x82)
	/usr/local/go/src/reflect/value.go:234 +0x13a
reflect.Value.SetInt(0x56a980, 0x5d7f98, 0x82, 0x2a)
	/usr/local/go/src/reflect/value.go:1542 +0x2f
github.com/mitchellh/mapstructure.(*Decoder).decodeInt(0xc0001aa008, 0x550b13, 0x5, 0x56a980, 0x5d7f98, 0x56a980, 0x5d7f98, 0x82, 0x82, 0x0)
[...]
	/home/benni/go/src/github.com/mitchellh/mapstructure/mapstructure.go:222 +0xf2
github.com/mitchellh/mapstructure.Decode(0x575860, 0xc000330000, 0x5620a0, 0xc0000d0080, 0x0, 0x0)
	/home/benni/go/src/github.com/mitchellh/mapstructure/mapstructure.go:130 +0x9f
github.com/mitchellh/mapstructure.Benchmark_DecodeBasic(0xc000232000)
	/home/benni/go/src/github.com/mitchellh/mapstructure/mapstructure_benchmark_test.go:79 +0x2f6
testing.(*B).runN(0xc000232000, 0x64)
	/usr/local/go/src/testing/benchmark.go:176 +0xb3
testing.(*B).launch(0xc000232000)
	/usr/local/go/src/testing/benchmark.go:328 +0xd1
created by testing.(*B).doBench
	/usr/local/go/src/testing/benchmark.go:294 +0x59
exit status 2
FAIL	github.com/mitchellh/mapstructure	2.990s
```

### Expected result:
Benchmarks complete

### Notes:
Tests complete just fine. When I remove line 74 in mapstructure_benchmark_test.go, 
```
		"vdata":   42,
```
the benchmark completes fine.

It seems like there is an issue destructuring into plain interface{}-es?

Thanks!

**Comment by mitchellh** [comment]
Should be fixed with #147. Thanks
