### ISSUE TITLE
panic reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by mghifariyusuf** [mitchellh/mapstructure#212]
### What I do

```
err = mapstructure.Decode(e, &m)
if err != nil {
	log.Println(err)
}
````

Value of m `map[]`

Value of e `&{9 Ribbon 2 <nil> 0xc0001e9d20 0xc0001e9d40 1 2 2020-11-09 09:25:31 +0000 UTC 2020-11-09 10:01:54 +0000 UTC 0xc0001e9d60 0xc0001e9d80}`

The struct

```
type Ribbon struct {
	ID                 int64
	Name               string
	LandscapeImageURL  *string
	PortraitImageURL   *string
	Portrait23ImageURL *string
	Status             int64
	ProjectID          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CreatedBy          *string
	LastUpdatedBy      *string
}
```

### What I got

```
server.go:3061: http: panic serving 127.0.0.1:58160: reflect: call of reflect.Value.Interface on zero Value
goroutine 55 [running]:
net/http.(*conn).serve.func1(0xc000564000)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:1772 +0x139
panic(0x1a22c40, 0xc0001e9fc0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:973 +0x396
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:998 +0x1a5
reflect.Value.Interface(...)
        /usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:993
github.com/mediocregopher/radix/v3/resp/resp2.Any.MarshalRESP(0x19c12c0, 0x0, 0x101, 0x1d19700, 0xc000197d50, 0x0, 0x0)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/resp/resp2/resp.go:600 +0xd9a
github.com/mediocregopher/radix/v3/resp/resp2.Any.MarshalRESP.func3(...)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/resp/resp2/resp.go:615
github.com/mediocregopher/radix/v3/resp/resp2.Any.MarshalRESP(0x1a316c0, 0xc0004370b0, 0x101, 0x1d19700, 0xc000197d50, 0x0, 0x0)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/resp/resp2/resp.go:639 +0xac0
github.com/mediocregopher/radix/v3/resp/resp2.Any.MarshalRESP.func3(...)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/resp/resp2/resp.go:615
github.com/mediocregopher/radix/v3/resp/resp2.Any.MarshalRESP(0x19cb220, 0xc0001e9fa0, 0x1d10101, 0x1d19700, 0xc000197d50, 0x0, 0x0)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/resp/resp2/resp.go:627 +0x770
github.com/mediocregopher/radix/v3.(*cmdAction).flatMarshalRESP(0xc00029e5b0, 0x1d19700, 0xc000197d50, 0x8, 0x8)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:272 +0x10c
github.com/mediocregopher/radix/v3.(*cmdAction).MarshalRESP(0xc00029e5b0, 0x1d19700, 0xc000197d50, 0xc00033f340, 0x10d05f5)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:277 +0x159
github.com/mediocregopher/radix/v3.pipeline.MarshalRESP(0xc0001e9f40, 0x2, 0x2, 0x1d19700, 0xc000197d50, 0x100836a, 0x8)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:483 +0x72
github.com/mediocregopher/radix/v3.(*connWrap).Encode(0xc0001e97e0, 0x1d1c160, 0xc0001e9f80, 0x100c28d, 0x20)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/radix.go:222 +0x4f
github.com/mediocregopher/radix/v3.(*ioErrConn).Encode(0xc0001e9800, 0x1d1c160, 0xc0001e9f80, 0xc0001e9f80, 0x0)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/pool.go:36 +0x4b
github.com/mediocregopher/radix/v3.pipeline.Run(0xc0001e9f40, 0x2, 0x2, 0x1d38440, 0xc0001e9800, 0x1f50f7c0, 0xb557e882ad39)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/action.go:461 +0x6d
github.com/mediocregopher/radix/v3.(*ioErrConn).Do(...)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/pool.go:52
github.com/mediocregopher/radix/v3.(*Pool).Do(0xc0001ca100, 0x1d29e80, 0xc0001e9f60, 0xc0001e9f60, 0xc0002683e0)
        /Users/ghifari/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.3.0/pool.go:585 +0xef
git.sstv.io/apps/video/api/videos.git/domain/ribbons/repository/radix.(*Radix).Get(0xc000138180, 0x1d352c0, 0xc00043e540, 0x2, 0x9, 0x100ef48, 0x10, 0x1a85000)
        /Users/ghifari/work/videos/domain/ribbons/repository/radix/radix.go:102 +0x853
git.sstv.io/apps/video/api/videos.git/service.(*svc).GetRibbon(0xc0000da000, 0x1d352c0, 0xc00043e540, 0xc000036150, 0x9, 0x0, 0x0)
        /Users/ghifari/work/videos/service/service_ribbons.go:119 +0x61
git.sstv.io/apps/video/api/videos.git/webserver/controller.(*handler).getRibbon(0xc000134500, 0x9c95370, 0xc0002b42c0, 0xc0001ca600)
        /Users/ghifari/work/videos/webserver/controller/ribbons.go:144 +0x245
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012
git.sstv.io/lib/go/go-auth-api.git/authpassport.(*Stdlib).OptionalAuthorize.func1(0x9c95370, 0xc0002b42c0, 0xc0001ca500)
        /Users/ghifari/go/pkg/mod/git.sstv.io/lib/go/go-auth-api.git@v0.0.0-20190716132433-665483f29d1e/authpassport/stdlib.go:122 +0x3c8
net/http.HandlerFunc.ServeHTTP(0xc0005b9e60, 0x9c95370, 0xc0002b42c0, 0xc0001ca500)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
github.com/newrelic/go-agent.WrapHandleFunc.func1(0x9c95370, 0xc0002b42c0, 0xc0001ca500)
        /Users/ghifari/go/pkg/mod/github.com/newrelic/go-agent@v2.10.0+incompatible/instrumentation.go:68 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc000281460, 0x9c95370, 0xc0002b42c0, 0xc0001ca500)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
github.com/rs/zerolog/hlog.AccessHandler.func1.1(0x1d317c0, 0xc00017e000, 0xc0001ca500)
        /Users/ghifari/go/pkg/mod/github.com/rs/zerolog@v1.15.0/hlog/hlog.go:180 +0x240
net/http.HandlerFunc.ServeHTTP(0xc00018c020, 0x1d317c0, 0xc00017e000, 0xc0001ca500)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000163d50, 0x1d317c0, 0xc00017e000, 0xc0001ca300)
        /Users/ghifari/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 +0x112
git.sstv.io/apps/video/api/videos.git/webserver.setCors.func1(0x1d317c0, 0xc00017e000, 0xc0001ca300)
        /Users/ghifari/work/videos/webserver/webserver.go:169 +0x184
net/http.HandlerFunc.ServeHTTP(0xc0001e9660, 0x1d317c0, 0xc00017e000, 0xc0001ca300)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc000474540, 0x1d317c0, 0xc00017e000, 0xc0001ca300)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000564000, 0x1d35240, 0xc0002b40c0)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2933 +0x35c
```

### What I do

```
err = mapstructure.Decode(&e, &m)
if err != nil {
	log.Println(err)
}
```

### What I got

```
'' expected a map, got 'ptr'
```

**Comment by mitchellh** [comment]
I'm unable to reproduce this. Looking at your "What I do" section, it looks like it may be due to erroneous indirection (`&` usage). I was able to successfully decode a map to a struct and pushed a test just now to verify.
